name: Test Installing WP Dependencies (Dev mode)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    # Checkout files
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # node_modules
    - name: Cache dependencies
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
    - run: npm i
      if: steps.npm-cache.outputs.cache-hit != 'true'

    - run: chmod -R 777 ./ # Fix write permission problem.
    - name: Start wp-env
      run: npm run wp-env start

    # vendor
    - name: Cache vendor
      uses: actions/cache@v2
      id: vendor-cache
      with:
        path: vendor
        key: ${{ runner.os }}-${{ matrix.node-version }}-composer-${{ hashFiles('composer.lock') }}
    - run: npm run install:composer
      if: steps.vendor-cache.outputs.cache-hit != 'true'

    - name: Install WordPress dependencies
      run: npm run wp-env run cli bash wp-content/plugins/wp-react-plugin-boilerplate/bin/install-deps/exe.sh -- --dev $WP_REACT_GITHUB_SECRET
      env:
        WP_REACT_GITHUB_SECRET: ${{ secrets.WP_REACT_GITHUB_SECRET }}
